# Introdução ao NumPy aplicada ao fluxo de veículos

O NumPy (Numerical Python) é a biblioteca base para computação numérica em Python. Ele é usado para processar, transformar e calcular dados matemáticos e estatísticos em larga escala de forma rápida e eficiente.

# 1.Importando a biblioteca NumPy

In [ ]:
import numpy as np

#2.Array

array -> armazenamento de dados com dimensões diferentes como matriz, vetor ou tensor.

In [ ]:
v1 = np.array([1,2,3])

In [ ]:
v2 = np.array([-2,3,-1])

Abaixo observamos uma operação vetorial

In [ ]:
v1 + v2

array([-1,  5,  2])

Qual a diferença para uma operação com listas ?

In [ ]:
A = [1,2,3]

In [ ]:
B = [-2,3,-1]

Abaixo, observamos uma concatenação entre duas listas

In [ ]:
A + B

[1, 2, 3, -2, 3, -1]

#2.1 Criando um array

**observe que automaticamente temos uma organização definida, assim temos uma manipulação de matriz**

In [ ]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**Tipo de dado e a biblioteca utilizada**

In [ ]:
type(A)

numpy.ndarray

**np.zeros()**: utilizado para matrizes que precisam de linhas/colunas com valor zero.

no parênteses temos 3 dimensões, 1° quantidade de matrizes, 2° quantidade de linhas e 3° quantidade de colunas.

In [ ]:
zero_array =np.zeros(shape = (5,4,3))

In [ ]:
zero_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

**np.ones()**: seguimos a mesma lógica da questão anterior.

In [ ]:
um_array = np.ones((3,3))

In [ ]:
um_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**np.empty()**: teremos uma dimensão sem valores atribuídos

In [ ]:
vazio = np.empty((2,3))

In [ ]:
vazio

array([[2.13821176e-315, 0.00000000e+000, 5.43370149e-291],
       [1.25990588e-300, 1.39067116e-309, 2.68866374e-317]])

**np.arange**:teremos uma dimensão que utiliza um parâmetro do python chamado "range", em poderemos selecionar o intervalo de valores.

In [ ]:
intervalo = np.arange(10)

note, que recebemos o intervalo de 0 até n -1.

In [ ]:
intervalo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

O ```np.arange``` é utilizado como uma progressão aritmética,  sendo assim temos no parâmetro 1° começo, 2° fim, 3° passo.



In [ ]:
intervalo = np.arange(1,10,2)

**np.linspace()**: segue um intervalo em que temos uma lógica linear



Agora observamos que há uma divisão linearmente, com suas partes sendo escolhida o número 15 e seu "ponto final" verdadeiro.

In [ ]:
array_linear = np.linspace(0, 50, num = 15, endpoint= True)

In [ ]:
array_linear

array([ 0.        ,  3.57142857,  7.14285714, 10.71428571, 14.28571429,
       17.85714286, 21.42857143, 25.        , 28.57142857, 32.14285714,
       35.71428571, 39.28571429, 42.85714286, 46.42857143, 50.        ])

#3.Tamanho de um array

Há algumas formas de descobrirmos as informações sobre uma determinada dimensão, para isso usaremos como uma dimensão de exemplo, a variável ```
zero_array```.



Abaixo, temos a quantidade de matrizes, linhas e colunas respectivamente.

In [ ]:
zero_array.shape

(5, 4, 3)

Abaixo, temos a quantidade de valores da matriz

In [ ]:
zero_array.size

60

Abaixo, temos o número de dimensões.

In [ ]:
zero_array.ndim

3

#4.Transformando um Vetor (1-D) em uma matrix(2-D)

tinhamos um vetor uni-dimensional e iremos agregar á outra dimensão.

In [ ]:
A = np.array([1, 2, 3])
print(A)

[1 2 3]


```np.newaxis```: criamos um eixo novo

In [ ]:
A2 = A[np.newaxis,:]
print(A2.shape)
print(A2.ndim)
print(A2)

(1, 3)
2
[[1 2 3]]


Assim, mudamos o eixo e adicionamos um novo sentido a dimensão

In [ ]:
A3 = A[:, np.newaxis]
print(A2.shape)
print(A2.ndim)
print(A3)

(1, 3)
2
[[1]
 [2]
 [3]]


acessando valores na matriz

aqui, vemos a regra de intervalos de 0  á n-1, o 1? parâmetro é a linha 0 e o segundo parâmetro coluna 1, recebemos então, o valor 2.

In [ ]:
print(A2[0][1])

2


#5.Concatenando arrays

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C = np.concatenate ((A,B))
D = np.concatenate ((B,A))

In [ ]:
print(C)
print(D)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


#6.Consulta de itens na array

Na consulta de valors, podemos localizar com lógica relacional e automaticamente é separado da array, sua resposta.

In [ ]:
A = np.array([[1,2,3,4,5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Vamos verificar números múltiplos de 5

In [ ]:
mult_5 = A[A % 5 == 0]
print(mult_5)

[ 5 10 15]


E se quisermos receber valores booleanos?

In [ ]:
mult_5 = (A % 5 == 0)
print(mult_5)

[[False False False False  True]
 [False False False False  True]
 [False False False False  True]]


# 7.Operações com Arrays

Podemos utilizar operações com arrays da seguinte forma:

ele também nos retorna o ```type``` do valor.



**Adição**

In [ ]:
A = np.array([1, 2, 3])

In [ ]:
A.sum()

np.int64(6)

**Valor mínimo**

In [ ]:
A.min()

np.int64(1)

**Valor máximo**

In [ ]:
A.max()

np.int64(3)

**Valor médio**

In [ ]:
A.mean()

np.float64(2.0)

8.Qual a diferença entre Arrays e Listas?

**Abaixo, temos 2 exemplos com a mesma quantidade de números e iguais, porém observamos que sua execução é diferente e seu ```type``` também.**

In [ ]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(A)
print(type(A))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
lista_A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(lista_A)
print(type(lista_A))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


Vamos adicionar uma ```string``` dentro dos parâmetros, assim percebemos a mudança de comportamento.



In [ ]:
A = np.array([1, "Sarah", 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(A)
print(type(A))

['1' 'Sarah' '2' '3' '4' '5' '6' '7' '8' '9' '10']
<class 'numpy.ndarray'>


In [ ]:
lista_A = [1, "Sarah", 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(lista_A)
print(type(lista_A))

[1, 'Sarah', 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


Note, que o comportamento da array selecionou todos os números como uma string. isso acontece devido á característica da array ser manipulação do mesmo tipo de dados, sem exibição da virgula e de grande volume de dados.